// ***********************************************************************
// Assembly         : WatsonSTT.Net.UnitTest
// Author           : jzielke
// Created          : 12-03-2016
//
// Last Modified By : jzielke
// Last Modified On : 12-05-2016
// ***********************************************************************
// <copyright file="WatsonSTT.Net.Test.cs" company="">
//     Copyright ©  2016
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Windows.Input;
using System.Windows.Forms;
using System.Drawing;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using WatsonSTT.Net;

namespace WatsonSTT.Net.UnitTest
{
    /// <summary>
    /// Summary description
    /// </summary>
    [TestClass()]
    public class WatsonSTTTest
    {
        #region Additional test attributes

        // You can use the following additional attributes as you write your tests:

        ////Use TestInitialize to run code before running each test 
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{        
        //    // To generate code for this test, select "Generate Code for Coded UI Test" from the shortcut menu and select one of the menu items.
        //}

        ////Use TestCleanup to run code after each test has run
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{        
        //    // To generate code for this test, select "Generate Code for Coded UI Test" from the shortcut menu and select one of the menu items.
        //}

        #endregion

        /// <summary>
        /// Gets or sets the test context which provides
        /// information about and functionality for the current test run.
        /// </summary>
        /// <value>The test context.</value>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        /// <summary>
        /// The test context instance
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for testContextInstance
        private TestContext testContextInstance;

        /// <summary>
        /// Speech to text test.
        /// </summary>
        /// <autogeneratedoc />
        [TestMethod()]
        public void GetSpeechTextTest()
        {
            string URL = @"https://watson-api-explorer.mybluemix.net/speech-to-text/api/v1/recognize";
            
            WatsonSTTClient target = new WatsonSTTClient(URL, "<GUID>", "<PASSWORD>");

            // Speech To Text API Documentation - https://goo.gl/3NPbfM
            target.QueryString.Add("model", "en-US_NarrowbandModel");
            target.QueryString.Add("continuous", "true");
            target.QueryString.Add("smart_formatting", "true");

            target.ContentType = "audio/wav; rate=8000";

            var TextMsg = target.SpeechToText(@"D:\Temp\69_20161204123540593.WAV");

            var VoiceMsg = "";
            var Confidence = 0.0;
            var Counter = 0;

            if (TextMsg != null)
            {
                foreach (var Line in TextMsg.results)
                {
                    if (Line.final == true)
                    {
                        foreach (var Alt in Line.alternatives)
                        {
                            Counter++;
                            Confidence += Alt.confidence;
                            VoiceMsg += Alt.transcript;
                        }
                    }
                }

                Confidence /= Counter;
            }            
        }
    }
}
